### PR TITLE
Non binary qualifier support for Context Algorithm

### PR DESCRIPTION
**Pull request by vmenger**
* Added support for non-binary qualifiers to the Context Algorithm. Resolves conflicts by looking at the closest modifier, than check the priority attribute.

### CODE REVIEW

**Comment by vmenger** [comment]
Fixes #39

**Review by mjhdoeleman — APPROVED** [review]
I think it would help to add docstrings to explainimportant classes or functions for new users of clinlp or future reviewers. Other than that, LGTM!

**Review by mjhdoeleman — APPROVED** [review]

**Review by mjhdoeleman — APPROVED** [review]
LGTM

**Comment by vmenger** [comment]
Fixes #39.

**Pull request merged**
